#!/bin/sh
# Find unique 9-digit polydivisible number, where...
# - each digit 1-9 appears exactly once and
# - the first n digits are divisible by n.

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# Filter out all numbers containing 0, reduce numbers by checking for simple
# division rules (odd/even) and remove numbers with duplicate digits.
# These filters will improve search performance alot!
apply_filters() {
	grep -v 0 \
		| grep -E '[1379][2468][1379][2468]5[1379][2468][1379][2468]' \
		| grep -Ev '(.).*\1'
}

validate_polydivisible() {
	awk '
	{
		is_valid = 1
		for (pos = 1; pos <= 9; pos++) {
			prefix = substr($0, 1, pos)
			if (prefix % pos != 0) {
				is_valid = 0
				break
			}
		}
		if (is_valid) print $0
	}'
}

seq -f '%09.0f' 123456789 987654321 \
	| apply_filters \
	| validate_polydivisible
