#!/bin/sh
# Find unique 9-digit polydivisible number, where...
# - each digit 1-9 appears exactly once and
# - the first n digits are divisible by n.

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# These filters will improve search performance alot by removing obvious
# invalid numbers from the list.
apply_filters() {
	grep -v 0 \
		| grep -E '\d{4}5\d{4}' \
		| grep -E '\d[2468]\d{3}[2468]\d{3}' \
		| grep -Ev '(.).*\1'
}

find_polydivisible() {
	awk '
	{
		is_valid = 1
		for (pos = 1; pos <= 9; pos++) {
			prefix = substr($0, 1, pos)
			if (prefix % pos != 0) {
				is_valid = 0
				break
			}
		}
		if (is_valid) print $0
	}'
}

seq -f '%09.0f' 0 999999999 \
	| apply_filters \
	| find_polydivisible
